flowchart TD
    subgraph SENSORICA ["Capa de Captura y Sensores"]
        CAM["Cámara Vial / RTSP / Video demo.mp4"]
        CALL_BTN["Botonera Peatonal / Mando C5"]
    end

    subgraph PROCESAMIENTO ["Procesamiento e Inferencia Edge"]
        PRE["Normalización 640x640"]
        INFER["Inferencia Dual: NPU RKNN / CPU PyTorch"]
        POST["Postprocesamiento y NMS"]
        TRACKER["BYTETracker - IDs Únicos"]
        ROI["Filtro Espacial de ROIs"]
        TSP["Ponderación Matemática TSP"]
    end

    subgraph FSM_CORE ["Máquina de Estados Finitos"]
        FSM["CoreSemaforo - FSM Adaptativa"]
        CLEARANCE["Protocolo Despeje: Ámbar y Todo-Rojo"]
        EMERGENCY["Controlador de Emergencia C5"]
        SUSTAIN["Cálculo de CO2 y Ahorro Energético"]
    end

    subgraph HARDWARE_OUTPUT ["Controladores Físicos"]
        ARDUINO["Arduino UNO R4 / PLC / Relevadores"]
        LIGHTS["Cabezales Semafóricos Físicos"]
        CONTROLLER_EX["Controlador Existente NEMA / 170 / 2070"]
    end

    subgraph SERVICIOS ["Servicios Web y Base de Datos"]
        MARIADB[("MariaDB - Persistencia Asíncrona")]
        FLASK_API["Servidor Flask y API REST"]
        SCADA["Consola SCADA C5 - /admin"]
        PUBLIC_PORTAL["Portal Ciudadano y V2X - /"]
        VIOLATIONS["Módulo Forense de Infracciones"]
    end

    CAM --> PRE
    CALL_BTN --> FSM
    PRE --> INFER
    INFER --> POST
    POST --> TRACKER
    TRACKER --> ROI
    ROI --> TSP
    TSP --> FSM

    FSM --- CLEARANCE
    FSM --- EMERGENCY
    FSM --> SUSTAIN

    FSM -->|Comandos Seriales| ARDUINO
    ARDUINO --> LIGHTS
    ARDUINO -.->|Integración Gabinete| CONTROLLER_EX

    FSM -->|Eventos y Telemetría| FLASK_API
    FSM -->|Cola Asíncrona| MARIADB
    FSM -->|Detección Infracciones| VIOLATIONS

    FLASK_API --> SCADA
    FLASK_API --> PUBLIC_PORTAL
    VIOLATIONS --> MARIADB
