graph TD
    subgraph SENSORICA [Capa de Captura y Sensores]
        CAM[Camara Vial / RTSP / Video demo.mp4]
        CALL_BTN[Boton Peatonal / Mando C5]
    end

    subgraph PROCESAMIENTO [Procesamiento e Inferencia Edge]
        PRE[Normalizacion 640x640]
        INFER[Inferencia Dual: NPU RKNN / CPU PyTorch]
        POST[Postprocesamiento y NMS]
        TRACKER[BYTETracker - IDs Unicos]
        ROI[Filtro Espacial de ROIs]
        TSP[Ponderacion Matematica TSP]
    end

    subgraph FSM_CORE [Maquina de Estados Finitos]
        FSM[CoreSemaforo - FSM Adaptativa]
        CLEARANCE[Protocolo Despeje: Ambar y Todo-Rojo]
        EMERGENCY[Controlador de Emergencia C5]
        SUSTAIN[Calculo de CO2 y Ahorro Energetico]
    end

    subgraph HARDWARE_OUTPUT [Controladores Fisicos]
        ARDUINO[Arduino UNO R4 / PLC / Relevadores]
        LIGHTS[Cabezales Semaforicos Fisicos]
        CONTROLLER_EX[Controlador Existente NEMA / 170 / 2070]
    end

    subgraph SERVICIOS [Servicios Web y Base de Datos]
        MARIADB[(MariaDB - Persistencia Asincrona)]
        FLASK_API[Servidor Flask y API REST]
        SCADA[Consola SCADA C5 - /admin]
        PUBLIC_PORTAL[Portal Ciudadano y V2X - /]
        VIOLATIONS[Modulo Forense de Infracciones]
    end

    CAM --> PRE
    CALL_BTN --> FSM
    PRE --> INFER
    INFER --> POST
    POST --> TRACKER
    TRACKER --> ROI
    ROI --> TSP
    TSP --> FSM

    FSM --- CLEARANCE
    FSM --- EMERGENCY
    FSM --> SUSTAIN

    FSM -->|Comandos Seriales| ARDUINO
    ARDUINO --> LIGHTS
    ARDUINO -.->|Integracion Gabinete| CONTROLLER_EX

    FSM -->|Eventos y Telemetria| FLASK_API
    FSM -->|Cola Asincrona| MARIADB
    FSM -->|Deteccion Infracciones| VIOLATIONS

    FLASK_API --> SCADA
    FLASK_API --> PUBLIC_PORTAL
    VIOLATIONS --> MARIADB
